# Generated by Django 5.2.12 on 2026-03-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_funcionario_cpf_funcionario_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cadastro_pendente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(condition=models.Q(('cnpj', ''), _negated=True), fields=('cnpj',), name='uq_empresa_cnpj_preenchido'),
        ),
    ]
