# Generated by Django 5.2.12 on 2026-03-25 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('funcionarios', 'Funcionários'), ('catraca', 'Catraca'), ('alocacao', 'Alocação'), ('projetos', 'Projetos'), ('outro', 'Outro')], max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('concluido_parcial', 'Concluído com ressalvas'), ('erro', 'Erro')], default='pendente', max_length=30)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='importacoes/%Y/%m/')),
                ('nome_arquivo_original', models.CharField(blank=True, default='', max_length=255)),
                ('total_linhas', models.PositiveIntegerField(default=0)),
                ('linhas_processadas', models.PositiveIntegerField(default=0)),
                ('linhas_com_erro', models.PositiveIntegerField(default=0)),
                ('resumo', models.JSONField(blank=True, default=dict)),
                ('erros', models.JSONField(blank=True, default=list)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importação',
                'verbose_name_plural': 'Importações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
