# Generated by Django 5.2.12 on 2026-03-10 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('codigo_atividade', models.CharField(max_length=50)),
                ('descr_atividade', models.CharField(max_length=255)),
                ('codigo_subatividade', models.CharField(blank=True, max_length=50)),
                ('descr_subatividade', models.CharField(blank=True, max_length=255)),
                ('qtd_escopo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unidade', models.CharField(max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral')], default='integral', max_length=20)),
                ('status_planejado', models.CharField(max_length=50)),
                ('area_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_cronograma', to='cadastros.arealocal')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_cronograma', to='cadastros.disciplina')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_cronograma', to='cadastros.projeto')),
            ],
            options={
                'ordering': ('data_inicio', 'codigo_atividade'),
                'constraints': [models.CheckConstraint(condition=models.Q(('data_fim__gte', models.F('data_inicio'))), name='ck_cronograma_data_fim_gte_inicio')],
            },
        ),
    ]


