# Generated by Django 6.0.3 on 2026-03-11 12:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('planejamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data', models.DateField()),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral')], max_length=20)),
                ('dia_semana', models.CharField(blank=True, max_length=20)),
                ('condicao_area', models.CharField(blank=True, max_length=255)),
                ('clima_manha', models.CharField(blank=True, max_length=60)),
                ('clima_tarde', models.CharField(blank=True, max_length=60)),
                ('clima_noite', models.CharField(blank=True, max_length=60)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pre_preenchido', 'Pré-preenchido'), ('em_revisao', 'Em revisão'), ('aprovado', 'Aprovado'), ('fechado', 'Fechado')], default='rascunho', max_length=20)),
                ('area_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rdcs', to='cadastros.arealocal')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rdcs_criados', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rdcs', to='cadastros.disciplina')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rdcs', to='cadastros.projeto')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdcs_supervisionados', to='cadastros.funcionario')),
            ],
            options={
                'ordering': ('-data', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='RDCAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('codigo_atividade', models.CharField(max_length=50)),
                ('descr_atividade', models.CharField(max_length=255)),
                ('codigo_subatividade', models.CharField(blank=True, max_length=50)),
                ('descr_subatividade', models.CharField(blank=True, max_length=255)),
                ('qtd_escopo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qtd_executada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comentarios', models.TextField(blank=True)),
                ('origem', models.CharField(choices=[('cronograma', 'Cronograma'), ('manual', 'Manual'), ('ajuste_supervisor', 'Ajuste do supervisor')], default='cronograma', max_length=20)),
                ('obrigatoria', models.BooleanField(default=False)),
                ('ativa_no_dia', models.BooleanField(default=True)),
                ('atividade_cronograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdcs_gerados', to='planejamento.atividadecronograma')),
                ('rdc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='rdc.rdc')),
            ],
            options={
                'ordering': ('codigo_atividade', 'codigo_subatividade'),
            },
        ),
        migrations.CreateModel(
            name='RDCFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('matricula', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=255)),
                ('hora_normal', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=6)),
                ('hora_extra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('hh_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('presente_catraca', models.BooleanField(default=False)),
                ('elegivel', models.BooleanField(default=True)),
                ('motivo_bloqueio', models.CharField(blank=True, max_length=255)),
                ('confirmado_supervisor', models.BooleanField(default=False)),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdcs_funcionarios', to='cadastros.equipe')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rdcs_funcionarios', to='cadastros.funcao')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rdcs_participacoes', to='cadastros.funcionario')),
                ('rdc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='rdc.rdc')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='RDCApontamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('horas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacao', models.TextField(blank=True)),
                ('rdc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='rdc.rdc')),
                ('rdc_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='rdc.rdcatividade')),
                ('rdc_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='rdc.rdcfuncionario')),
            ],
            options={
                'ordering': ('rdc_funcionario__nome',),
            },
        ),
        migrations.CreateModel(
            name='RDCValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('funcionario_sem_catraca', 'Funcionário sem catraca'), ('funcionario_sem_alocacao', 'Funcionário sem alocAção'), ('atividade_fora_cronograma', 'Atividade fora do cronograma'), ('funcao_divergente', 'Função divergente'), ('equipe_fora_histograma', 'Equipe fora do histograma'), ('duplicidade_apontamento', 'Duplicidade de apontamento')], max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('alerta', 'Alerta'), ('bloqueio', 'Bloqueio'), ('info', 'Informativo')], default='info', max_length=20)),
                ('mensagem', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rdc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validacoes', to='rdc.rdc')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='rdc',
            constraint=models.UniqueConstraint(fields=('projeto', 'area_local', 'disciplina', 'data', 'turno'), name='uq_rdc_contexto_diario'),
        ),
        migrations.AddConstraint(
            model_name='rdcatividade',
            constraint=models.UniqueConstraint(fields=('rdc', 'codigo_atividade', 'codigo_subatividade', 'origem'), name='uq_rdc_atividade_unica'),
        ),
        migrations.AddConstraint(
            model_name='rdcfuncionario',
            constraint=models.UniqueConstraint(fields=('rdc', 'funcionario'), name='uq_rdc_funcionario_unico'),
        ),
        migrations.AddConstraint(
            model_name='rdcapontamento',
            constraint=models.UniqueConstraint(fields=('rdc', 'rdc_funcionario', 'rdc_atividade'), name='uq_rdc_apontamento_unico'),
        ),
    ]

