# Generated by Django 5.2.12 on 2026-03-13 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_empresa_cadastro_pendente_empresa_observacoes_and_more'),
        ('rdc', '0009_pacote_premium'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilOperacionalUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True)),
                ('disciplina_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_operacionais_rdc', to='cadastros.disciplina')),
                ('equipe_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_operacionais_rdc', to='cadastros.equipe')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfis_operacionais_rdc', to='cadastros.funcionario')),
                ('projeto_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_operacionais_rdc', to='cadastros.projeto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_operacional_rdc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil operacional do usuário',
                'verbose_name_plural': 'Perfis operacionais dos usuários',
                'ordering': ('user__username',),
            },
        ),
        migrations.CreateModel(
            name='CalendarioPlanejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data', models.DateField()),
                ('ano', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('semana_codigo', models.CharField(db_index=True, max_length=10)),
                ('semana_numero', models.PositiveSmallIntegerField()),
                ('semana_label', models.CharField(blank=True, max_length=40)),
                ('data_inicio_semana', models.DateField()),
                ('data_fim_semana', models.DateField()),
                ('dia_semana', models.PositiveSmallIntegerField(help_text='0=Segunda ... 6=Domingo')),
                ('dia_semana_nome', models.CharField(max_length=20)),
                ('eh_dia_util', models.BooleanField(default=True)),
                ('eh_feriado', models.BooleanField(default=False)),
                ('descricao_evento', models.CharField(blank=True, max_length=255)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios_planejamento', to='cadastros.projeto')),
            ],
            options={
                'verbose_name': 'Calendário do planejamento',
                'verbose_name_plural': 'Calendários do planejamento',
                'ordering': ('data',),
                'indexes': [models.Index(fields=['projeto', 'semana_codigo'], name='idx_cal_proj_semana'), models.Index(fields=['projeto', 'data'], name='idx_cal_proj_data')],
                'constraints': [models.UniqueConstraint(fields=('projeto', 'data'), name='uq_calendario_planejamento_projeto_data')],
            },
        ),
    ]


