# Generated by Django 5.2.12 on 2026-03-16 12:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_empresa_cadastro_pendente_empresa_observacoes_and_more'),
        ('planejamento', '0001_initial'),
        ('rdc', '0010_perfiloperacionalusuario_calendarioplanejamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacaoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('semana_codigo', models.CharField(db_index=True, max_length=10)),
                ('semana_label', models.CharField(blank=True, max_length=40)),
                ('data_inicio_semana', models.DateField(blank=True, null=True)),
                ('data_fim_semana', models.DateField(blank=True, null=True)),
                ('data_programada', models.DateField(blank=True, null=True)),
                ('codigo_atividade', models.CharField(max_length=50)),
                ('descr_atividade', models.CharField(max_length=255)),
                ('codigo_subatividade', models.CharField(blank=True, max_length=50)),
                ('descr_subatividade', models.CharField(blank=True, max_length=255)),
                ('qtd_prevista', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('hh_previsto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral')], default='integral', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('origem_arquivo', models.CharField(blank=True, max_length=255)),
                ('area_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programacoes_semanais', to='cadastros.arealocal')),
                ('atividade_cronograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programacoes_semanais', to='planejamento.atividadecronograma')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programacoes_semanais', to='cadastros.disciplina')),
                ('encarregado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programacoes_semanais', to='cadastros.funcionario')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programacoes_semanais', to='cadastros.equipe')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacoes_semanais', to='cadastros.projeto')),
            ],
            options={
                'verbose_name': 'ProgramAção semanal',
                'verbose_name_plural': 'Programações semanais',
                'ordering': ('projeto__codigo', 'semana_codigo', 'codigo_atividade'),
                'indexes': [models.Index(fields=['projeto', 'semana_codigo'], name='idx_prog_proj_semana'), models.Index(fields=['projeto', 'data_programada'], name='idx_prog_proj_data')],
            },
        ),
    ]


