# Generated by Django 5.2.12 on 2026-03-16 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdc', '0011_programacaosemanal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rdcfuncionario',
            name='justificativa_liberacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rdcfuncionario',
            name='liberado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdcfuncionario',
            name='liberado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdcs_funcionarios_liberados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rdcfuncionario',
            name='liberado_sem_catraca',
            field=models.BooleanField(default=False),
        ),
    ]

