# Generated by Django 5.2.12 on 2026-03-10 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes_funcionarios', to='cadastros.disciplina')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_funcionarios', to='cadastros.equipe')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='cadastros.funcionario')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes_funcionarios', to='cadastros.projeto')),
            ],
            options={
                'ordering': ('-data_inicio', 'funcionario__nome'),
                'constraints': [models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), ('data_fim__gte', models.F('data_inicio')), _connector='OR'), name='ck_alocacao_data_fim_gte_inicio')],
            },
        ),
        migrations.CreateModel(
            name='HistogramaPlanejado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quantidade_planejada', models.PositiveIntegerField()),
                ('data', models.DateField()),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral')], default='integral', max_length=20)),
                ('area_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histogramas', to='cadastros.arealocal')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histogramas', to='cadastros.disciplina')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histogramas', to='cadastros.equipe')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histogramas', to='cadastros.funcao')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histogramas', to='cadastros.projeto')),
            ],
            options={
                'ordering': ('-data', 'projeto__nome'),
                'constraints': [models.UniqueConstraint(fields=('projeto', 'area_local', 'disciplina', 'equipe', 'funcao', 'data', 'turno'), name='uq_histograma_planejado_contexto')],
            },
        ),
    ]

