# Generated by Django 5.2.12 on 2026-03-10 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCatraca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data', models.DateField()),
                ('matricula', models.CharField(db_index=True, max_length=30)),
                ('entrada_1', models.TimeField(blank=True, null=True)),
                ('saida_1', models.TimeField(blank=True, null=True)),
                ('entrada_2', models.TimeField(blank=True, null=True)),
                ('saida_2', models.TimeField(blank=True, null=True)),
                ('presente', models.BooleanField(default=False)),
                ('origem_arquivo', models.CharField(max_length=255)),
                ('observacao', models.TextField(blank=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_catraca', to='cadastros.funcionario')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_catraca', to='cadastros.projeto')),
            ],
            options={
                'ordering': ('-data', 'matricula'),
                'constraints': [models.UniqueConstraint(fields=('data', 'matricula', 'origem_arquivo'), name='uq_catraca_data_matricula_origem')],
            },
        ),
    ]

