# Generated by Django 5.2.12 on 2026-03-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0001_initial'),
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registrocatraca',
            name='uq_catraca_data_matricula_origem',
        ),
        migrations.AddConstraint(
            model_name='registrocatraca',
            constraint=models.UniqueConstraint(fields=('data', 'matricula'), name='uq_registro_catraca_data_matricula'),
        ),
    ]

