# Generated by Django 6.0.3 on 2026-03-11 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('funcionarios', 'Funcionários'), ('catraca', 'Catraca'), ('alocacoes', 'AlocaçÃµes'), ('cronograma', 'Cronograma'), ('histograma', 'Histograma')], max_length=30)),
                ('arquivo', models.FileField(upload_to='importacoes/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('concluido_com_erros', 'Concluído com erros'), ('erro', 'Erro')], default='pendente', max_length=30)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes_arquivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportacaoErro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.PositiveIntegerField()),
                ('campo', models.CharField(blank=True, max_length=100)),
                ('mensagem', models.TextField()),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erros', to='importacoes.importacaoarquivo')),
            ],
            options={
                'ordering': ('importacao_id', 'linha', 'id'),
            },
        ),
    ]

