# Generated by Django 5.2.12 on 2026-03-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importacaoerro',
            options={'ordering': ('linha', 'id')},
        ),
        migrations.AlterField(
            model_name='importacaoarquivo',
            name='tipo',
            field=models.CharField(choices=[('funcionarios', 'Funcionários'), ('catraca', 'Catraca'), ('alocacoes', 'AlocaçÃµes'), ('cronograma', 'Cronograma'), ('histograma', 'Histograma')], max_length=30),
        ),
    ]

