# Generated by Django 5.2.12 on 2026-03-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importacoes', '0002_alter_importacaoerro_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importacaoerro',
            options={'ordering': ('importacao_id', 'linha', 'id')},
        ),
    ]

