# Generated by Django 5.2.12 on 2026-03-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacoes', '0003_alter_importacaoerro_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaoarquivo',
            name='resumo',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
