from django.urls import path

from rdc.views import (
    RDCAuditoriaExportView,
    RDCAtividadeBuscaView,
    RDCAtividadeCreateView,
    
    RDCAtividadeInlineUpdateView,
    RDCAtividadeLoteView,
    RDCAtividadeUpdateView,
    RDCConsolidadoExportView,
    RDCConsolidadoView,
    RDCDeleteView,
    RDCAuditoriaDashboardView,
    RDCDashboardHomeView,
    RDCDetailView,
    RDCExportView,
    RDCExportarModeloView,
    RDCFuncionarioBuscaView,
    RDCFuncionarioCreateView,
    RDCFuncionarioDeleteView,
    RDCFuncionarioInlineUpdateView,
    RDCFuncionarioLoteView,
    RDCFuncionarioUpdateView,
    RDCImportarAtividadesCronogramaView,
    RDCImportarFuncionariosAlocacaoView,
    RDCListView,
    RDCMontagemView,
    RDCApontamentoCreateView,
    RDCApontamentoDeleteView,
    RDCApontamentoInlineUpdateView,  # 👈 ADICIONA AQUI
    RDCApontamentoLoteView,
    RDCApontamentoUpdateView,
    RDCRevalidarView,
    RDCUpdateView,
    RDCValidacaoCreateView,
    RDCValidacaoDeleteView,
    RDCValidacaoInlineUpdateView,
    RDCValidacaoLoteView,
    RDCValidacaoUpdateView,
    RDCValidacoesView,
    RDCWorkflowView,
    RDOExportView,
    RDOView,
)

urlpatterns = [
    path("<int:pk>/apontamentos/<int:pk2>/inline-update/",
         name="rdc-apontamento-inline-update"),

    path(
        "<int:pk>/funcionarios/<int:pk2>/inline-update/",
        name="rdc-funcionario-inline-update",
    ),

    path(
        "consolidado/exportar/<str:tipo>/",
        name="rdc-consolidado-export",
    ),
    path(
        "<int:pk>/exportar-modelo/",
        name="rdc-exportar-modelo",
    ),
    path(
        "<int:pk>/auditoria/exportar/",
        name="rdc-auditoria-exportar",
    ),
    path("<int:pk>/exportar/<str:tipo>/", RDCExportView.as_view(), name="rdc-export"),
    path(
        "<int:pk>/buscar-atividades/",
        name="rdc-atividade-busca",
    ),
    path(
        "<int:pk>/buscar-funcionarios/",
        name="rdc-funcionario-busca",
    ),
    path(
        "<int:pk>/importar-atividades-cronograma/",
        name="rdc-importar-atividades-cronograma",
    ),
    path(
        "<int:pk>/importar-funcionarios-alocacao/",
        name="rdc-importar-funcionarios-alocacao",
    ),
    path(
        "<int:pk>/atividades/novo/",
        name="rdc-atividade-create",
    ),
    path(
        "<int:pk>/atividades/<int:pk2>/editar/",
        name="rdc-atividade-update",
    ),
    path(
        "<int:pk>/atividades/<int:pk2>/excluir/",
        name="rdc-atividade-delete",
    ),
    path(
        "<int:pk>/atividades/<int:pk2>/inline-update/",
        name="rdc-atividade-inline-update",
    ),
    path(
        "<int:pk>/atividades/lote/",
        name="rdc-atividade-lote",
    ),
    path(
        "<int:pk>/funcionarios/novo/",
        name="rdc-funcionario-create",
    ),
    path(
        "<int:pk>/funcionarios/<int:pk2>/editar/",
        name="rdc-funcionario-update",
    ),
    path(
        "<int:pk>/funcionarios/<int:pk2>/excluir/",
        name="rdc-funcionario-delete",
    ),
    path(
        "<int:pk>/funcionarios/lote/",
        name="rdc-funcionario-lote",
    ),
    path(
        "<int:pk>/apontamentos/novo/",
        name="rdc-apontamento-create",
    ),
    path(
        "<int:pk>/apontamentos/<int:pk2>/editar/",
        name="rdc-apontamento-update",
    ),
    path(
        "<int:pk>/apontamentos/<int:pk2>/excluir/",
        name="rdc-apontamento-delete",
    ),
    path(
        "<int:pk>/apontamentos/lote/",
        name="rdc-apontamento-lote",
    ),
    path(
        "<int:pk>/validacoes/nova/",
        name="rdc-validacao-create",
    ),
    path(
        "<int:pk>/validacoes/<int:pk2>/editar/",
        name="rdc-validacao-update",
    ),
    path(
        "<int:pk>/validacoes/<int:pk2>/excluir/",
        name="rdc-validacao-delete",
    ),
    path(
        "<int:pk>/validacoes/<int:pk2>/inline-update/",
        name="rdc-validacao-inline-update",
    ),
    path(
        "<int:pk>/validacoes/lote/",
        name="rdc-validacao-lote",
    ),
]

